name: Demo customers service pipeline
on:
  push:
    branches: "**"
jobs:
  run_test:
    name: run tests
    strategy:
      matrix:
        node-version: [22.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Jest
        run: npm install jest
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: jest run test
        run: |
          npm run test
        env:
          CI: true
  deploy_source:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [22.x]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/amer-transaction-changes'
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
      - name: Remove .git directory
        run: |
          rm -rf .git
      - name: zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./bundle.zip ./
      - name: default deploy
        if: github.ref == 'refs/heads/main' || 'refs/heads/dev' || 'refs/heads/dynamic_links'
        uses: appleboy/lambda-action@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
        with:
          function_name: demo_customerFunction
          zip_file: bundle.zip
